name: blockchain_authentication_repository
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.3.3
  blockchain_provider: 
    path: ../blockchain_provider
  secure_storage:
    path: ../secure_storage
  json_annotation: ^4.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: