name: multi_spaces
description: Decentralized cross-platform storage solution.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2

  http: ^1.1.0 # ^0.13.5
  equatable: ^2.0.5
  # flutter_envify: ^3.0.1
  envied: ^0.3.0+3
  # walletconnect_dart: ^0.0.11
  walletconnect_flutter_v2: ^2.0.12
  web3dart: 2.7.1 #^2.5.3
  web3auth_flutter: ^1.0.3
  qr_flutter: ^4.1.0
  

  blockchain_provider: 
    path: './packages/blockchain_provider'
  blockchain_repository: 
    path: './packages/blockchain_repository'
  blockchain_authentication_repository: 
    path: './packages/blockchain_authentication_repository'
  user_repository: 
    path: './packages/user_repository'
  secure_storage: 
    path: './packages/secure_storage'
  ipfs_repository: 
    path: './packages/ipfs_repository'
  infura_ipfs_api: 
    path: './packages/infura_ipfs_api'
  pinata_ipfs_api: 
    path: './packages/pinata_ipfs_api'
  crust_ipfs_api: 
    path: './packages/crust_ipfs_api'
  key_repository: 
    path: './packages/key_repository'
  file_storage_repository: 
    path: './packages/file_storage_repository'

  dartz: ^0.10.1
  url_launcher: ^6.1.7
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0 
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.14
  formz: ^0.4.1
  flutter_secure_storage: ^7.0.1
  modal_bottom_sheet: ^2.1.2
  awesome_dialog: ^3.0.2
  logger: ^1.1.0
  convert: ^3.1.1
  eth_sig_util: ^0.0.9
  provider: ^6.0.5
  flutter_slidable: ^2.0.0
  json_theme: ^4.0.3+4
  flutter_expandable_fab: ^2.0.0
  universal_html: ^2.2.1
  encrypt: ^5.0.1
  pointycastle: ^3.7.2
  asn1lib: ^1.4.0
  secp256k1: ^0.3.0 
  simple_gradient_text: ^1.2.4
  file_picker: ^5.2.10
  hive: ^2.2.3
  cryptography_flutter: ^2.2.0
  uuid: ^3.0.7
  async: ^2.10.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.2.0
  retry: ^3.1.2
  badges: ^3.1.2
  web_socket_channel: ^2.4.0
  app_links: ^3.4.5
  share_plus: ^7.1.0
  open_app_file: ^4.0.2
  swipeable_button_view: ^0.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  analyzer: 
  build_runner:
  # flutter_envify_generator: 
  envied_generator: ^0.3.0+3
  web3dart_builders: ^0.0.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/theme_dark.json
    - assets/theme_light.json