name: blockchain_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  walletconnect_dart: ^0.0.11
  web3dart: ^2.3.3
  blockchain_provider: 
    path: ../blockchain_provider
  eth_sig_util: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: