const String WEB3_AUTH_PRIV_KEY = "WEB3_AUTH_PRIV_KEY";
const String WEB3_AUTH_EMAIL_KEY = "WEB3_AUTH_EMAIL_KEY";
const String WEB3_AUTH_NAME_KEY = "WEB3_AUTH_NAME_KEY";
const String WEB3_AUTH_PROFILE_KEY = "WEB3_AUTH_PROFILE_KEY";
